

INSERT INTO user ( usernamename)  
VALUES ("John Smith")
INSERT INTO user ( usernamename)  
VALUES ("Joan Smith")
INSERT INTO user ( usernamename)  
VALUES ("John Doe")
INSERT INTO user ( usernamename)  
VALUES ("Jane Smith")
INSERT INTO user ( usernamename)  
VALUES ("Jane Smith")
INSERT INTO user ( usernamename)  
VALUES ("Silas Marner")
INSERT INTO user ( usernamename)  
VALUES ("Michael Jackson")
INSERT INTO user ( usernamename)  
VALUES ("Darth Vader")
INSERT INTO user ( usernamename)  
VALUES ("John Q Public")

